#!/usr/bin/env bash
# =============================================================================
# WTF LivePulse — Build, Push & Deploy (run on every release)
# Usage: ./deploy/deploy.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Load infra config generated by infra.sh
if [[ ! -f "$SCRIPT_DIR/.env.deploy" ]]; then
  echo "❌  .env.deploy not found. Run ./deploy/infra.sh first."
  exit 1
fi
source "$SCRIPT_DIR/.env.deploy"

BACKEND_IMAGE="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$APP/backend"
FRONTEND_IMAGE="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$APP/frontend"
TAG="${IMAGE_TAG:-$(git rev-parse --short HEAD 2>/dev/null || date +%s)}"

echo "════════════════════════════════════════"
echo "  WTF LivePulse — Deploy"
echo "  Tag: $TAG  |  Region: $REGION"
echo "════════════════════════════════════════"

# ── 1. ECR Login ──────────────────────────────────────────────────────────────
echo ""
echo "[1/4] Logging in to ECR..."
aws ecr get-login-password --region "$REGION" \
  | docker login --username AWS --password-stdin \
      "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"
echo "  ✓ ECR login"

# ── 2. Build + Push Images ────────────────────────────────────────────────────
echo ""
echo "[2/4] Building & pushing images..."

ROOT="$(dirname "$SCRIPT_DIR")"

# Backend
echo "  Building backend..."
docker build \
  --platform linux/amd64 \
  -t "$BACKEND_IMAGE:$TAG" \
  -t "$BACKEND_IMAGE:latest" \
  "$ROOT/backend"
docker push "$BACKEND_IMAGE:$TAG"
docker push "$BACKEND_IMAGE:latest"
echo "  ✓ Backend pushed: $BACKEND_IMAGE:$TAG"

# Frontend — pass ALB backend URL as build arg
BACKEND_API_URL="${VITE_API_URL:-http://$ALB_DNS}"
echo "  Building frontend (VITE_API_URL=$BACKEND_API_URL)..."
docker build \
  --platform linux/amd64 \
  --build-arg VITE_API_URL="$BACKEND_API_URL" \
  -t "$FRONTEND_IMAGE:$TAG" \
  -t "$FRONTEND_IMAGE:latest" \
  "$ROOT/frontend"
docker push "$FRONTEND_IMAGE:$TAG"
docker push "$FRONTEND_IMAGE:latest"
echo "  ✓ Frontend pushed: $FRONTEND_IMAGE:$TAG"

# ── 3. Register ECS Task Definitions ──────────────────────────────────────────
echo ""
echo "[3/4] Registering ECS task definitions..."

TMPDIR_TASKS=$(mktemp -d)
trap 'rm -rf "$TMPDIR_TASKS"' EXIT

# Backend task def — write to temp file (macOS doesn't support /dev/stdin with aws cli)
cat > "$TMPDIR_TASKS/backend.json" <<EOF
{
  "family": "${APP}-backend",
  "networkMode": "awsvpc",
  "requiresCompatibilities": ["FARGATE"],
  "cpu": "512",
  "memory": "1024",
  "executionRoleArn": "${ROLE_ARN}",
  "taskRoleArn": "${ROLE_ARN}",
  "containerDefinitions": [
    {
      "name": "backend",
      "image": "${BACKEND_IMAGE}:${TAG}",
      "essential": true,
      "portMappings": [{"containerPort": 3001, "protocol": "tcp"}],
      "environment": [
        {"name": "PORT",     "value": "3001"},
        {"name": "NODE_ENV", "value": "production"}
      ],
      "secrets": [
        {"name": "DATABASE_URL", "valueFrom": "${DATABASE_URL_SECRET_ARN}"}
      ],
      "healthCheck": {
        "command":     ["CMD-SHELL", "wget -qO- http://localhost:3001/api/health || exit 1"],
        "interval":    30,
        "timeout":     5,
        "retries":     3,
        "startPeriod": 60
      },
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group":         "/ecs/${APP}/backend",
          "awslogs-region":        "${REGION}",
          "awslogs-stream-prefix": "ecs"
        }
      }
    }
  ]
}
EOF

BACKEND_TASK_ARN=$(aws ecs register-task-definition \
    --cli-input-json "file://$TMPDIR_TASKS/backend.json" \
    --region "$REGION" \
    --query 'taskDefinition.taskDefinitionArn' --output text)
echo "  ✓ Backend task def: $BACKEND_TASK_ARN"

# Frontend task def
cat > "$TMPDIR_TASKS/frontend.json" <<EOF
{
  "family": "${APP}-frontend",
  "networkMode": "awsvpc",
  "requiresCompatibilities": ["FARGATE"],
  "cpu": "256",
  "memory": "512",
  "executionRoleArn": "${ROLE_ARN}",
  "containerDefinitions": [
    {
      "name": "frontend",
      "image": "${FRONTEND_IMAGE}:${TAG}",
      "essential": true,
      "portMappings": [{"containerPort": 80, "protocol": "tcp"}],
      "environment": [
        {"name": "BACKEND_URL", "value": "http://${ALB_DNS}"}
      ],
      "healthCheck": {
        "command":     ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"],
        "interval":    30,
        "timeout":     5,
        "retries":     3,
        "startPeriod": 30
      },
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group":         "/ecs/${APP}/frontend",
          "awslogs-region":        "${REGION}",
          "awslogs-stream-prefix": "ecs"
        }
      }
    }
  ]
}
EOF

FRONTEND_TASK_ARN=$(aws ecs register-task-definition \
    --cli-input-json "file://$TMPDIR_TASKS/frontend.json" \
    --region "$REGION" \
    --query 'taskDefinition.taskDefinitionArn' --output text)
echo "  ✓ Frontend task def: $FRONTEND_TASK_ARN"

# ── 4. Create / Update ECS Services ───────────────────────────────────────────
echo ""
echo "[4/4] Deploying ECS services..."

_deploy_service() {
  local NAME=$1 TASK_ARN=$2 TG_ARN=$3 PORT=$4

  EXISTS=$(aws ecs describe-services \
    --cluster "$APP" --services "$NAME" \
    --region "$REGION" \
    --query 'services[0].status' --output text 2>/dev/null || echo "INACTIVE")

  if [[ "$EXISTS" == "ACTIVE" ]]; then
    aws ecs update-service \
      --cluster "$APP" \
      --service "$NAME" \
      --task-definition "$TASK_ARN" \
      --force-new-deployment \
      --region "$REGION" &>/dev/null
    echo "  ✓ Updated: $NAME"
  else
    aws ecs create-service \
      --cluster "$APP" \
      --service-name "$NAME" \
      --task-definition "$TASK_ARN" \
      --desired-count 1 \
      --launch-type FARGATE \
      --network-configuration "awsvpcConfiguration={subnets=[$PUB_SUBNET_A,$PUB_SUBNET_B],securityGroups=[$ECS_SG],assignPublicIp=ENABLED}" \
      --load-balancers "targetGroupArn=$TG_ARN,containerName=$(echo $NAME | sed 's/.*-//'),containerPort=$PORT" \
      --health-check-grace-period-seconds 120 \
      --region "$REGION" &>/dev/null
    echo "  ✓ Created: $NAME"
  fi
}

_deploy_service "$APP-backend"  "$BACKEND_TASK_ARN"  "$TG_BACKEND"  3001
_deploy_service "$APP-frontend" "$FRONTEND_TASK_ARN" "$TG_FRONTEND" 80

echo ""
echo "  Waiting for services to stabilize (may take 2-3 min)..."
aws ecs wait services-stable \
  --cluster "$APP" \
  --services "$APP-backend" "$APP-frontend" \
  --region "$REGION"

echo ""
echo "════════════════════════════════════════"
echo "  ✅ Deployment complete!"
echo ""
echo "  🌐  http://$ALB_DNS"
echo ""
echo "  Tip: bookmark that URL — it's your live app!"
echo "════════════════════════════════════════"
